services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app/.env
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - app-data:/app/static

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local